### ISSUE TITLE
devkit install throws error

### ISSUE THREAD

**Issue by rampr** [CodeCombiner/native-android#8]
```
➜  mygame git:(hc) ✗        ../src/devkit.js install
(node:69296) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
         [install]  Installing devkit-core@hc...
                    Adding devkit-core@hc
          [module]  [warn]  Your module has files we don't recognize in it. This is normally ok, but in some cases it can prevent devkit from updating your module. If an error occurs, you should consider removing these files and then running this command again:
                    modules/native-ios/node_modules/
                    (/Users/rampr/work/hashcube/gradle/devkit/mygame/modules/devkit-core)
                    running install scripts...

> devkit-core@4.5.3-43 preinstall /Users/rampr/work/hashcube/gradle/devkit/mygame/modules/devkit-core
> sh scripts/preinstall.sh

Synchronizing submodule url for 'modules/native-android'
```
Synchronizing submodule url for 'modules/native-ios'
Synchronizing submodule url for 'modules/squill'
Synchronizing submodule url for 'modules/timestep'
Submodule path 'modules/native-android': checked out '6744219e817ed5148894bfb782834eac12d2c65e'

> native-android@1.0.23 preinstall /Users/rampr/work/hashcube/gradle/devkit/mygame/modules/devkit-core/modules/native-android
> sh ./preinstall.sh

Synchronizing submodule url for 'native-core'

> native-android@1.0.23 postinstall /Users/rampr/work/hashcube/gradle/devkit/mygame/modules/devkit-core/modules/native-android
> node checkSymlinks && (make setup && make clean || true)

Makefile:68: *** missing separator.  Stop.
```
```

**Comment by rampr** [comment]
I found the issue to be spaces instead of tabs in line 68.
So I added tabs at at that line and I came across another error

gradlew doesn't exist

So I tried adding
gradle wrapper before ./gradlew clean in the Makefile

Now I have the following error

> gradle wrapper
> Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details
> 
> BUILD SUCCESSFUL in 2s
> 1 actionable task: 1 up-to-date
> ./gradlew clean
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Task 'clean' not found in root project 'native-android'.
> 
> * Try:
> Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org

**Comment by rampr** [comment]
I added this and I was able to move forward - not sure if that was the intention
`./gradleops/AndroidSeed/gradlew -b gradleops/AndroidSeed/build.gradle clean`

**Comment by rampr** [comment]
devkit debug now fails with the following error

```
 ➜  sudoku-quest-mobile git:(gradle) ✗ devkit debug native-android
           [build]  starting build at Sat Jun 16 2018 14:57:47 GMT+0530 (IST)
(node:75259) DeprecationWarning: 'GLOBAL' is deprecated, use 'global'
            [apps]  /Users/rampr/work/hashcube/sudoku-quest-mobile/manifest.json
           [build]  [error]
⤷  tryOnImmediate (timers.js:543)
 ⤷  Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/async.js:15)
  ⤷  Async._drainQueues (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/async.js:133)
   ⤷  Async._drainQueue (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/async.js:128)
    ⤷  MappingPromiseArray.init (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/map.js:29)
     ⤷  MappingPromiseArray.init (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/promise_array.js:92)
      ⤷  MappingPromiseArray._promiseFulfilled (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/map.js:56)
       ⤷  tryCatcher (/usr/local/lib/node_modules/devkit/node_modules/bluebird/js/main/util.js:26)
        ⤷  undefined (/usr/local/lib/node_modules/devkit/src/build/steps/buildHooks.js:70)
         ⤷  loadExtension (/usr/local/lib/node_modules/devkit/src/modules/Module.js:91)
          ⤷  require (internal/module.js:20)
           ⤷  Module.require (module.js:468)
            ⤷  Function.Module._load (module.js:409)
             ⤷  tryModuleLoad (module.js:417)
              ⤷  Module.load (module.js:458)
               ⤷  Object.Module._extensions..js (module.js:550)
                ⤷  Module._compile (module.js:541)
                 ⤷  Object.<anonymous> (/Users/rampr/work/hashcube/sudoku-quest-mobile/modules/firebase/build/index.js:5)
                  ⤷  require (internal/module.js:20)
                   ⤷  Module.require (module.js:468)
                    ⤷  Function.Module._load (module.js:388)
                     ⤷  Function.Module._resolveFilename (module.js:440)
                     Error: Cannot find module '../../devkit-core/modules/native-ios/lib/xcodeUtil'
                    build failed
```

**Comment by CodeCombiner** [comment]
Please remove everything you added because the error is not related
https://github.com/CodeCombiner/native-android/issues/8#issuecomment-397798779
It just allows to perform couple steps forward to wrong direction after the main error raised.
I am testing newly pushed source code

**Comment by CodeCombiner** [comment]
Please, attach manifest.json file. I will check plugins you use. Before I tested to built apks with the plugins I have updated  only. I have faced before with the empty Manifest.xml before.
FYI running `native-android@1.0.23 postinstall ` has been removed in latest commits. You need to update submodules or clone `devkit` again.

To update submodules:
1. Update module first:
git pull
2. Open terminal at
`devkit/testgame/modules/devkit-core/`
3. Paste and run 
`git submodule update --init --force --remote`

Detailed instruction to update submodules:
https://stackoverflow.com/questions/5828324/update-git-submodule-to-latest-commit-on-origin/21195182

Please post new questions or next errors to continue fixing

**Comment by rampr** [comment]
Please find the manifest.json (uploaded as txt)
[manifest.txt](https://github.com/CodeCombiner/native-android/files/2109135/manifest.txt)

I will try the other things you have mentioned and will let you know how it goes

**Comment by rampr** [comment]
I've tried it with the latest submodule, but still the error with the empty AndroidManifest.xml exists

**Comment by rampr** [comment]
The error in Makefile during devkit install also still is present after updating the submodules

**Comment by CodeCombiner** [comment]
I think this issue appears because some assets for firebase plugin are missed or some settings are not provided , the error:
```
⤷  Object.<anonymous> (/Users/rampr/work/hashcube/sudoku-quest-mobile/modules/firebase/build/index.js:5)
                  ⤷  require (internal/module.js:20)
                   ⤷  Module.require (module.js:468)
                    ⤷  Function.Module._load (module.js:388)
                     ⤷  Function.Module._resolveFilename (module.js:440)
                     Error: Cannot find module '../../devkit-core/modules/native-ios/lib/xcodeUtil'
                    build failed
```


And indeed, devkit-core missed this module
```
devkit-core/modules/native-ios/lib/xcodeUtil
``` 

This has been fixed by changing `native-core` submodule branch to `hc`

Please remove `devkit-core` from devkit cache and run again

**Comment by CodeCombiner** [comment]
I need additional files to run the project.
 Error: Cannot find module '.../devkit/sqmtest/assets/google/android_test.json'

The settings in manifest:
`  "firebase": {
      "android": "assets/google/android_test.json",
      "ios": "assets/google/ios_test.plist"
    }
`

**Comment by rampr** [comment]
Uploading android_test.json as txt

[android_test.txt](https://github.com/CodeCombiner/native-android/files/2110422/android_test.txt)

**Comment by rampr** [comment]
This particular error still exists during devkit install

`./gradlew: No such file or directory`

Full trace below:

> > devkit-core@4.5.3-43 preinstall /Users/rampr/work/hashcube/sudoku-quest-mobile/modules/devkit-core
> > sh scripts/preinstall.sh
> 
> Synchronizing submodule url for 'modules/native-android'
> Synchronizing submodule url for 'modules/native-ios'
> Synchronizing submodule url for 'modules/squill'
> Synchronizing submodule url for 'modules/timestep'
> Submodule path 'modules/native-android': checked out '3e10bfbc2395f8668be8eaa8e7b93e6d3f3e1267'
> 
> > native-android@1.0.23 preinstall /Users/rampr/work/hashcube/sudoku-quest-mobile/modules/devkit-core/modules/native-android
> > sh ./preinstall.sh
> 
> Synchronizing submodule url for 'native-core'
> 
> > native-android@1.0.23 postinstall /Users/rampr/work/hashcube/sudoku-quest-mobile/modules/devkit-core/modules/native-android
> > node checkSymlinks && (make setup && make clean || true)
> 
> node checkSymlinks
> ./gradlew clean
> make: ./gradlew: No such file or directory
> make: *** [clean] Error 1
> npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
> npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
> 
> > native-ios@2.0.0 preinstall /Users/rampr/work/hashcube/sudoku-quest-mobile/modules/devkit-core/modules/native-ios
> > sh ./preinstall.sh
> 
> Submodule 'barista' (https://github.com/gameclosure/barista.git) registered for path 'barista'
> Submodule 'tealeaf/deps/jansson' (https://github.com/gameclosure/jansson.git) registered for path 'tealeaf/deps/jansson'
> Submodule 'tealeaf/native-core' (https://github.com/hashcube/native-core.git) registered for path 'tealeaf/native-core'

**Comment by CodeCombiner** [comment]
https://github.com/CodeCombiner/native-android/issues/8#issuecomment-397888567
Fixed

**Comment by CodeCombiner** [comment]
https://github.com/CodeCombiner/native-android/issues/8#issuecomment-399841908
Fixed

**Comment by CodeCombiner** [comment]
Just reopen it if some issues raise.

**Comment by rampr** [comment]
This issue is still there, I'm unable to reopen it

**Comment by rampr** [comment]
The only issue that remains here is -> https://github.com/CodeCombiner/native-android/issues/8#issuecomment-399841908

**Comment by CodeCombiner** [comment]
Done

**Comment by CodeCombiner** [comment]
`./gradlew: No such file or directory` removed

**Comment by rampr** [comment]
That error is gone, there is a new one though:
**make: *** No rule to make target `clean'.  Stop.**

Here is the log: 

```
Synchronizing submodule url for 'modules/squill'
Synchronizing submodule url for 'modules/timestep'
Submodule path 'modules/native-android': checked out 'a54d8ba6448512ec3a8a7c65b2467d0949086d1b'

> native-android@1.0.23 preinstall /Users/rampr/work/hashcube/sudoku-quest-mobile/modules/devkit-core/modules/native-android
> sh ./preinstall.sh

Synchronizing submodule url for 'native-core'


> native-android@1.0.23 postinstall /Users/rampr/work/hashcube/sudoku-quest-mobile/modules/devkit-core/modules/native-android
> node checkSymlinks && (make setup && make clean || true)

node checkSymlinks
make: *** No rule to make target `clean'.  Stop.

> native-ios@2.0.0 preinstall /Users/rampr/work/hashcube/sudoku-quest-mobile/modules/devkit-core/modules/native-ios
> sh ./preinstall.sh
```

**Comment by CodeCombiner** [comment]
Fixed

**Comment by rampr** [comment]
I still see this error
make: *** No rule to make target `clean'.  Stop.

**Comment by CodeCombiner** [comment]
Fixed, PR https://github.com/hashcube/native-android/pull/49

**Comment by rampr** [comment]
Will check, node checkSymlinks isn't needed anymore Alex ?

**Comment by CodeCombiner** [comment]
Correct, it is now in devkit-core android-native.js

**Comment by rampr** [comment]
Got it. Will verify and close

**Comment by rampr** [comment]
This is fixed
